spring:
  application:
    name: kafka-demo
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    # Default to 30 seconds
    maxPollIntervalMs: 30000